### ISSUE TITLE
Upload PDF to Amazon S3

### ISSUE THREAD

**Issue by barredterra** [alyf-de/erpnext_pdf-on-submit#2]
Every time a PDF is attached to a **Quotation**, **Sales Order** or **Sales Invoice**, it should be uploaded to S3. The S3 folder should be protected from deletion.

Reference implementation: **S3 Backup Settings**.

**Comment by DrZoidberg09** [comment]
That would be such a nice addition @barredterra 
Any plans if and when to implement?

**Comment by barredterra** [comment]
Not planned right now, therefore closing this issue.

An easy solution might be to install https://github.com/frappe/storage_integration, which can upload PDFs to S3 (along with all other files).

**Comment by DrZoidberg09** [comment]
@barredterra That is exactly what I tried :)

However, it spits out "IsADirectoryError: [Errno 21] Is a directory: " when it is supposed to store/upload the PDF.

Problem is: I have no clue whose "fault" it is. Do you have any clue if that is coming from this app or the storage_integration app?

Thank you so much!

**Comment by barredterra** [comment]
This app tries to create a folder structure for the PDFs. Maybe the S3 integration doesn't support that yet?

**Comment by DrZoidberg09** [comment]
That is what I also thought initially. I will look into that and come back.

The combination of the PDF on submit and S3 would be really awesome.
